/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'apps-cours-and-group': RouteRecordInfo<'apps-cours-and-group', '/apps/cours-and-group', Record<never, never>, Record<never, never>>,
    'apps-programs-cours': RouteRecordInfo<'apps-programs-cours', '/apps/programs/cours', Record<never, never>, Record<never, never>>,
    'apps-programs-groups': RouteRecordInfo<'apps-programs-groups', '/apps/programs/groups', Record<never, never>, Record<never, never>>,
    'apps-students': RouteRecordInfo<'apps-students', '/apps/students', Record<never, never>, Record<never, never>>,
    'apps-students-id': RouteRecordInfo<'apps-students-id', '/apps/students/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
  }
}
